FROM python:3.10.16-alpine3.21
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache \
    build-base \
    mariadb-dev
#RUN apk add --no-cache gcc musl-dev linux-headers
WORKDIR /code
COPY requirements.txt /code
RUN pip install -r requirements.txt
COPY . /code
